import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, appendFile, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { savings, formatSavings, recordRouting } from '../plugins/openshunt/lib/savings.mjs';
import { recordUsage, delegate } from '../plugins/openshunt/lib/delegate.mjs';
import { handlePreTool } from '../plugins/openshunt/lib/hooks.mjs';
import { spawnCapture } from '../plugins/openshunt/lib/worker.mjs';
async function fixture(t) {const cwd=await mkdtemp(path.join(os.tmpdir(),'openshunt-savings-'));t.after(()=>rm(cwd,{recursive:true,force:true}));await mkdir(path.join(cwd,'.git'));return {cwd,env:{...process.env,OPENSHUNT_WORKER_ACTIVE:'',OPENSHUNT_ENABLED:'1',OPENSHUNT_TRACKING:'1',XDG_CONFIG_HOME:path.join(cwd,'config'),XDG_STATE_HOME:path.join(cwd,'state')}};}
test('empty savings is explicit about unknown native and monetary savings',async t=>{
 const {env}=await fixture(t);const r=await savings(env);assert.equal(r.completedCliCalls,0);assert.equal(r.moneySaved,null);assert.equal(r.firstRecordedAt,null);assert.match(formatSavings(r),/No recorded delegations/);
});
test('routing records only metadata and deduplicates repeated host tool IDs',async t=>{
 const {cwd,env}=await fixture(t);await writeFile(path.join(cwd,'large'),'private\n'.repeat(351));
 const e={cwd,session_id:'private-session',tool_use_id:'read-1',tool_name:'Read',tool_input:{file_path:path.join(cwd,'large')}};
 await handlePreTool(e,env);await handlePreTool(e,env);
 const spawn={cwd,session_id:'private-session',tool_use_id:'spawn-1',tool_name:'Agent',tool_input:{subagent_type:'openshunt:bulk-reader',model:'haiku',prompt:'SECRET_TASK'}};
 await handlePreTool(spawn,env);await handlePreTool(spawn,env);
 await handlePreTool({...spawn,tool_use_id:'rejected',tool_input:{...spawn.tool_input,model:'opus'}},env);
 const r=await savings(env);assert.equal(r.blockedReadAttempts,1);assert.equal(r.nativeDelegationAttempts,1);assert.equal(r.completedCliCalls,0);
 assert.equal(r.byModel[0].model,'haiku');
 const raw=await readFile(path.join(env.XDG_STATE_HOME,'openshunt/routing.jsonl'),'utf8');
 for(const secret of [cwd,'SECRET_TASK','private-session','file_path']) assert.ok(!raw.includes(secret));
});
test('provider usage and legacy estimates stay separate; corrupt rows do not inflate totals',async t=>{
 const {env}=await fixture(t);
 await recordUsage({mode:'bulk-reader',worker:'claude',model:'haiku',usage:{input_tokens:3,cache_read_input_tokens:8},estimatedParentInputTokensAvoided:20,contextEstimateVersion:1},env);
 await recordUsage({mode:'code-writer',worker:'codex',model:'luna',usage:{input_tokens:10},estimatedParentInputTokensAvoided:40},env);
 await appendFile(path.join(env.XDG_STATE_HOME,'openshunt/usage.jsonl'),'null\n{"mode":"unexpected"}\nBROKEN\n');
 const r=await savings(env);assert.equal(r.completedCliCalls,2);assert.equal(r.contextSavings.estimatedTokensExcluded,20);assert.equal(r.contextSavings.legacyEstimatedTokens,40);assert.equal(r.byModel[0].reportedUsage.cache_read_input_tokens,8);assert.equal(r.byModel[1].reportedUsage.input_tokens,10);assert.equal(r.moneySaved,null);
});
test('tracking can be disabled without disabling routing; disk failures preserve denial',async t=>{
 const {cwd,env}=await fixture(t);const disabled={...env,OPENSHUNT_TRACKING:'0'};
 await recordRouting('native_attempt',{}, {},disabled);await recordUsage({mode:'bulk-reader'},disabled);
 assert.equal((await savings(env)).nativeDelegationAttempts,0);
 await writeFile(path.join(cwd,'large'),'x\n'.repeat(351));
 await writeFile(path.join(cwd,'not-a-directory'),'x');
 const result=await handlePreTool({cwd,tool_name:'Read',tool_input:{file_path:path.join(cwd,'large')}},{...env,XDG_STATE_HOME:path.join(cwd,'not-a-directory')});
 assert.equal(result.hookSpecificOutput.permissionDecision,'deny');
});
test('CLI estimates use source or generated bytes, never system prompt overhead',async t=>{
 const {cwd,env}=await fixture(t);const executable=path.join(cwd,'fake-worker');
 await writeFile(executable,`#!/usr/bin/env node\nprocess.stdin.resume();process.stdin.on('end',()=>console.log(JSON.stringify({type:'result',subtype:'success',result:'small answer'})));\n`,{mode:0o755});
 await writeFile(path.join(cwd,'source'),'x'.repeat(400));
 const config={worker:'claude',model:'haiku',executable,maxInputBytes:1048576,timeoutMs:5000};
 const r=await delegate({mode:'bulk-reader',task:'a long question '.repeat(30),files:['source'],config,cwd,env});
 assert.equal(r.record.sourceBytes,400);assert.equal(r.record.estimatedParentInputTokensAvoided,97);
 const w=await delegate({mode:'code-writer',task:'Generate',files:['source'],config,cwd,env});
 assert.equal(w.record.estimatedParentInputTokensAvoided,0); // Code returned to parent: no context kept out.
 const result=await spawnCapture(process.execPath,[path.resolve('plugins/openshunt/scripts/openshunt.mjs'),'savings','--json'],{cwd,env});
 assert.equal(result.code,0);assert.equal(JSON.parse(result.stdout).completedCliCalls,2);
 await writeFile(executable,`#!/usr/bin/env node\nprocess.stdin.resume();process.stdin.on('end',()=>console.log(JSON.stringify({type:'result',subtype:'success',result:'x'.repeat(400)})));\n`,{mode:0o755});
 const disk=await delegate({mode:'code-writer',task:'Generate',files:['source'],target:'target',config,cwd,env});
 assert.ok(disk.record.estimatedParentInputTokensAvoided>0);
 assert.equal((await readFile(path.join(cwd,'target'))).length,401);
 await assert.rejects(delegate({mode:'code-writer',task:'Generate',files:['source'],target:'target',config,cwd,env}),/exists/);
 assert.equal((await savings(env)).completedCliCalls,3);
});
